eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
server:
  port: 8087
spring:
  application:
    name: ribbon-provider
